[package]
name = "gen_gdext"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29.0" }
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_yaml = "0.9.33"
